// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ555k6VhWMabSN7r93ZaC8pXeM8naU5c',
    appId: '1:48529370548:web:fef5eafa77562967f056e1',
    messagingSenderId: '48529370548',
    projectId: 'your-training-app',
    authDomain: 'your-training-app.firebaseapp.com',
    storageBucket: 'your-training-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDenMStIxR7ypqnHA8qfjU_xfSITsaDHM8',
    appId: '1:48529370548:android:1765101f88a465f6f056e1',
    messagingSenderId: '48529370548',
    projectId: 'your-training-app',
    storageBucket: 'your-training-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6JyGgErfa1apwPK23uVrJNDSRNRPyjeU',
    appId: '1:48529370548:ios:c8ac8549ca95bdb8f056e1',
    messagingSenderId: '48529370548',
    projectId: 'your-training-app',
    storageBucket: 'your-training-app.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6JyGgErfa1apwPK23uVrJNDSRNRPyjeU',
    appId: '1:48529370548:ios:05d538bd949ccd3ef056e1',
    messagingSenderId: '48529370548',
    projectId: 'your-training-app',
    storageBucket: 'your-training-app.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ555k6VhWMabSN7r93ZaC8pXeM8naU5c',
    appId: '1:48529370548:web:f190aa5fa88e2ba8f056e1',
    messagingSenderId: '48529370548',
    projectId: 'your-training-app',
    authDomain: 'your-training-app.firebaseapp.com',
    storageBucket: 'your-training-app.firebasestorage.app',
  );
}
